### ISSUE TITLE
Polybar issue

### ISSUE THREAD

**Issue by Its-Kenta** [RandomLegend/dotfiles-comfycorner#2]
Hey, wonderful work with the rice! Just a quick one, getting the following error when trying to run Polybar:

```
notice: Parsing config file: /home/kenta/.config/polybar/config.ini
error: Uncaught exception, shutting down: The config file contains multiple bars, but no bar name was given. Available bars: 1, 2, 3, 4
```
Any idea why? I haven't touched the settings so they're what you provided.

**Comment by RandomLegend** [comment]
Thanks :-)

How do you run polybar? Because you have to explicitly tell it what bars you want to run.
I now see that i forgot to remove a bar that isn't used..

do `polybar 1 & polybar 3 & polybar 4`

That should give you what i have in my screenshots. If you want this to autostart you can add this command to whatever  script you use to autostart your stuff

**Comment by RandomLegend** [comment]
I will update the config to make more sense and make it use bar 1,2,3 instead of 1,3,4. Also rearrange it and remove bar2

I will also put the correct command to launch them all in the readme.

**Comment by Its-Kenta** [comment]
> Thanks :-)
> 
> How do you run polybar? Because you have to explicitly tell it what bars you want to run. I now see that i forgot to remove a bar that isn't used..
> 
> do `polybar 1 & polybar 3 & polybar 4`
> 
> That should give you what i have in my screenshots. If you want this to autostart you can add this command to whatever script you use to autostart your stuff

Ah I see, I wasn't aware how to run it frankly speaking.
~~How do you normally auto run it when KDE starts?~~ (You already mentioned it, didn't see. Sorry) Also would you have the font files to share by any chance?

**Comment by RandomLegend** [comment]
Alright, now if you redownload the repo you can run polybar with

polybar 1 & polybar 2 & polybar 3

Also i see that i completely botched the config, because i forgot to make it possible for all users...It was looking for my personal home directory. That's dumb...so now it should work.

Also, important. The weather addon was still using my API Token and City ID, that would make it completely useless for you. Take a look into the ~/.config/polybar/weather/config.toml file to get your specific token and ID to make it work for you.

**Comment by RandomLegend** [comment]
Ah i don't have to font files right now, but those are all easily available on the internet, nothing special

**Comment by Its-Kenta** [comment]
Sounds good thank you for speedy fix!

**Comment by RandomLegend** [comment]
Sure thing, if there is still something missing tell me! I want this to work and i am not really experienced in sharing my dotfiles...so i still have to learn how to do things to make them work for everyone :-D

**Comment by Its-Kenta** [comment]
Is there any special app required for xworkspaces? They (icons too) don't seem to appear on the polybar

**Comment by RandomLegend** [comment]
Not as far as i remember...you should check that all the scripts and binaries in the polybar config folder have permission to be executed.

You can open your console and execute polybar from there, you will then get precise logging of each action polybar does and what errors might occur.
